# Generated by Django 2.2.12 on 2021-02-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VyasProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Date_started', models.DateField()),
                ('Date_ended', models.DateField(blank=True)),
                ('Category', models.CharField(choices=[('award', 'Award'), ('favourite', 'Favourite'), ('code', 'Code'), ('community', 'Community')], default='Community', max_length=30)),
            ],
        ),
    ]
