# Generated by Django 2.2.12 on 2021-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_vyasprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vyasprofile',
            name='Date_ended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
